stages:
    - check
    - build
    - deploy_staging
    - deploy_production

variables:
    GIT_STRATEGY: clone

before_script:
    - git config --global --add safe.directory /builds/fajnovysport/fajnovysport

check_phpstan:
    stage: check
    image: php:8.1-cli
    script:
        - composer install
        - php vendor/bin/phpstan analyse wp/

check_and_build:
    stage: build
    image: fastestsolution/node22
    services:
        - docker:dind
    script:
        - npm ci --no-audit
        - task install
        - task check
        - task build
    only:
        - branches
    except:
        - master

deploy_staging:
    stage: deploy_staging
    image: fastestsolution/node22
    script:
        - task install
        - task build
        # TODO add copy to php and deploy zip to FTP
    only:
        - master
    dependencies:
        - check_phpstan
        - check_and_build

deploy_production:
    stage: deploy_production
    image: fastestsolution/node22
    script:
        - task install
        - task build

        # TODO add copy to php and deploy zip to FTP
    only:
        - manual
    when: manual
    dependencies:
        - check_phpstan
        - check_and_build
