name: CI Pipeline

on:
    push:
        branches:
            - "**"
    workflow_dispatch:

jobs:
    check_phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: php-actions/composer@v6

            - name: PHPStan Static Analysis
              uses: php-actions/phpstan@v3
              with:
                  path: wp/

    check_and_build:
        runs-on: ubuntu-latest
        container:
            image: fastestsolution/node22
            options: --user root
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Add safe directory for git
              run: git config --global --add safe.directory /__w/fajnovysport/fajnovysport

            - name: Install dependencies
              run: |
                  task install
              working-directory: ${{ github.workspace }}

            - name: Run checks
              run: task check
              working-directory: ${{ github.workspace }}

            - name: Build project
              run: task build
              working-directory: ${{ github.workspace }}
    deploy_staging:
        runs-on: ubuntu-latest
        container:
            image: fastestsolution/node22
            options: --user root
        needs: [check_phpstan, check_and_build]
        if: github.ref_name == 'master' && startsWith(github.event_name, 'push')
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Add safe directory for git
              run: git config --global --add safe.directory /__w/fajnovysport/fajnovysport

            - name: Install dependencies
              run: task install
              working-directory: ${{ github.workspace }}

            - name: Build project
              run: task build
              working-directory: ${{ github.workspace }}

    deploy_production:
        runs-on: ubuntu-latest
        container:
            image: fastestsolution/node22
            options: --user root
        needs: [check_phpstan, check_and_build]
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Add safe directory for git
              run: git config --global --add safe.directory /__w/fajnovysport/fajnovysport

            - name: Install dependencies
              run: task install
              working-directory: ${{ github.workspace }}

            - name: Build project
              run: task build
              working-directory: ${{ github.workspace }}
