name: CI Pipeline

on:
    push:
        branches:
            - "**"
    workflow_dispatch:

jobs:
    check_and_build:
        runs-on: ubuntu-latest
        container: fastestsolution/node22
        steps:
            - name: Install dependencies
              run: task install

            - name: Run checks
              run: task check

            - name: Build project
              run: task build

    deploy_staging:
        runs-on: ubuntu-latest
        container: fastestsolution/node22
        if: github.ref_name == 'master' && startsWith(github.event_name, 'push')
        steps:
            - name: Install dependencies
              run: task install

            - name: Run checks
              run: task check

            - name: Build project
              run: task build

    deploy_production:
        runs-on: ubuntu-latest
        container: fastestsolution/node22
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
        steps:
            - name: Install dependencies
              run: task install

            - name: Build project
              run: task build
