name: CI Pipeline

on:
    push:
        branches:
            - "**"
    workflow_dispatch:

jobs:
    check_and_build:
        runs-on: ubuntu-latest
        container:
            image: fastestsolution/node22
            options: --user root
            # volumes:
            #     - /www:${{ github.workspace }}
        steps:
            - name: Fix permissions for temp directory
              run: sudo chmod -R 777 /__w/_temp/
            - uses: actions/checkout@v3
            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x
            # - name: Configure Git safe directory
            #   run: git config --global --add safe.directory ${{ github.workspace }}

            - name: Debug current directory
              run: |
                  echo "Current directory:"
                  pwd
                  echo "Contents of directory:"
                  ls -al
            - name: Install dependencies
              run: |
                  task install
              env:
                  PATH: ${{ env.PATH }}:/usr/local/bin
              working-directory: ${{ github.workspace }}

            - name: Run checks
              run: task check
              working-directory: ${{ github.workspace }}

            - name: Build project
              run: task build
              working-directory: ${{ github.workspace }}

    deploy_staging:
        runs-on: ubuntu-latest
        container: fastestsolution/node22
        if: github.ref_name == 'master' && startsWith(github.event_name, 'push')
        steps:
            - name: Install dependencies
              run: task install
              working-directory: ${{ github.workspace }}

            - name: Run checks
              run: task check
              working-directory: ${{ github.workspace }}

            - name: Build project
              run: task build
              working-directory: ${{ github.workspace }}

    deploy_production:
        runs-on: ubuntu-latest
        container: fastestsolution/node22
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
        steps:
            - name: Install dependencies
              run: task install
              working-directory: ${{ github.workspace }}

            - name: Run checks
              run: task check
              working-directory: ${{ github.workspace }}

            - name: Build project
              run: task build
              working-directory: ${{ github.workspace }}
